name: End-to-End Tests (cypress)

on:
  push:
    paths:
      - "client/**"
      - ".github/workflows/cypress.yml"
      - "!**.md"

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          working-directory: ./client
