name: Client Tests

on: push

jobs:
  vitest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout this codebase
        uses: actions/checkout@v3
      - name: Set up Node 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm i
      - name: Run Vitest
        run: npm run vitest
  # TODO: test coverage report job