name: Client Tests (vitest)

on:
  push:
    paths:
      - .github/workflows/vitest.yml  # Watch changes to this workflow
      - client/**                     # and every file in the client app project
      - "!client/cypress**"           # except for the ones that belong to Cypress.
      - "!**.md"                      # Ignore documentation changes.

jobs:
  vitest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout this codebase
        uses: actions/checkout@v3
     
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
     
      - name: Install dependencies
        run: npm i
     
      - name: Run Vitest
        run: npm run test
  # TODO: test coverage report job
